@LibraryAppWebAPI_HostAddress = https://localhost:7145

GET {{LibraryAppWebAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{LibraryAppWebAPI_HostAddress}}/api/authors
Content-Type: application/json

{
  //Author

}

###
